### ISSUE TITLE
DATA: Review Digital Twin Newsroom Items

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/threefold_data#37]
- Open data_threefold repo
- Check each MD file in "news"
- Add, remove, or keep twin in category field, depending on if the newsroom item is relevant to Digital Twin or not.

*Ping me if you have any questions, brother.*

**Comment by Vilnite** [comment]
See in circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/78
