### ISSUE TITLE
Add more farmers to data base

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/threefold_data#49]
Let's get farmers data collected and add them to our data base. Both, People and Projects.

- [x] create a form to collect data from farmers
- [x] send out form
- [x] get a script in the Sheet going to automatically process the data into the format we need _(not prio if takes too much of a time - looks like a separate issue is needed for this)_
- [ ] put all received info in data_threefold

After @VonSub has gathered info, I'll make sure they are properly showed on our web presence.

**Comment by VonSub** [comment]
Created this: https://forms.gle/eFcNSzuZ7RbnAm3n8
Will work on a post with @samtaggart as soon as we think that the form is good enough.

**Comment by Sacha96** [comment]
@VonSub we are collecting only formal information there... we need content from the heart too! Why are they involved with threefold? What's the message they want to share to the world? Is there a quote we can get from them which shares why Farming is important for the world?

**Comment by VonSub** [comment]
> @VonSub we are collecting only formal information there... we need content from the heart too! Why are they involved with threefold? What's the message they want to share to the world? Is there a quote we can get from them which shares why Farming is important for the world?

@Sacha96 
![image](https://user-images.githubusercontent.com/29431263/124735332-3f58f080-df16-11eb-888a-a7addc8ef3cb.png)
We should reword this in that case, but keep in mind that for data_threefold we are bound to contraints of content. This is different to a farmer profile in a marketing story. Hence my comment that we need to keep the two separated.

**Comment by Sacha96** [comment]
Ok sounds goo let's do this and then get in touch with big & cool farmers for stories. Let's shoot!

**Comment by VonSub** [comment]
ok, the form is underwhelming AF. 4 replies so far.

I have a meeting with Blockheating, MWW, and Bruce as good as setup for the interviews.

**Comment by samtaggart** [comment]
@VonSub Keep bringing the form back to the farming group – every day. Things get lost there.
