### ISSUE TITLE
Change UI when clicking on the "Link" icon on Blog or Newsroom

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/threefold_data#54]
<img width="1108" alt="Screen Shot 2021-08-04 at 8 55 55 AM" src="https://user-images.githubusercontent.com/50134479/128129412-d6305488-ff31-42ba-9ac3-57e776622fad.png">

Currently, when clicking on the link icon next to Facebook, nothing happens visually. But it seems that it is copying the link for you. Is there anything we can do to make it more visually obvious that something is happening when you click the link icon?

**Comment by samtaggart** [comment]
@Vilnite I didn't assign a priority or a person. Maybe there's not even a solution. But I leave it to you and the web team.

**Comment by Vilnite** [comment]
I agree with Sam.

@samaradel can you please add a grey background colour that stays after clicking / or come up with an alternative so that a person clicking on the link icon is assured that its copied?
