### ISSUE TITLE
Update Wisdom Council Website 

### ISSUE THREAD

**Issue by Karoline888** [threefoldfoundation/threefold_data#55]
TF Foundation had Wisdom Council Call on 3rd of August
We have an update on members on ACI website: https://threefold.io/aci/wisdomcouncil

1)
- [x] Isabelle is not a member anymore, please take down her profile
- [x] Jennifer Long is not a member anymore, please take down her profile

2)
Karoline is collecting content from new members and uploading to TF_Data Repo to provide for Kristine necessary information to push new profiles live on website
New members:
- [x] Ali Mohsen
- [x] Florian Flourier
- [x] Thibault Verbiest
- [x] Rudy Bouwman

Content to be collected:
Full name: 
bio: 
linkedin: 
websites: (of involvement)
image: 
projects: (of involvement)
countries: 
cities: 
Video (a short video introducing themselves and sharing a bit about their commitment being part of a Wisdom Council(
Example other members for: https://www.consciousinternet.org/wisdomcouncil

- [x] double check on info_threefold

**Comment by Vilnite** [comment]
Here's the list after updates:
- Rishi Chidananda
- Michael Wellesley-Wesley
- Sophie Monpeyssen
- Adnan Fatayerji
- Dave de Belder
- Dimitrios Dementzioglou
- Kristof de Spiegeleer
- Owen Kemp
- Ali Mohsen
- Florian Flourier
- Thibault Verbiest
- Rudy Bouwman

@Karoline888 please approve.
