### ISSUE TITLE
people order

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/threefold_data#56]
https://threefold.io/people

maybe we should show main founders appear first: Kristof, Adnan, Raj, Weynand, Chris... then main connectors; Ewald, Owen, Florian, Michael, Winston Ma, YanLing and other business faces such as Michel Coucke, and main partners... we need to focus this website more for funding.

**Comment by Sacha96** [comment]
also remove maximilian from front

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/79
