### ISSUE TITLE
review all projects & people

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/threefold_data#71]
lots of info not up to date, lets fix it now

**Comment by despiegk** [comment]
maybe it should not happen here, but in other location seen the new webframework from timur

**Comment by sasha-astiadi** [comment]
make sure threefold.io (the current live version) have the latest projects and people

**Comment by sasha-astiadi** [comment]
https://www.threefold.io/partners/

@samtaggart maybe we should update the partners for next release? looks outdated.
