### ISSUE TITLE
how to remove people they have blogs

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldfoundation/threefold_data#89]
I moved people left to archive folder but can't move Hannah because she has many blogs and that ll break the author link and image ,any idea how we solve this?

**Comment by sasha-astiadi** [comment]
and add in every blog; "This article was originally published by Hannah Cordes, a former member of ThreeFold Foundation."

**Comment by ehab-hassan** [comment]
@sasha-astiadi @samtaggart ok let's have a list of all people left so we can update all people's page
I think (the jumper  team) left and Victoria Obeegadoo(she had some blogs).

**Comment by ehab-hassan** [comment]
upaded blogs and news author name
